spring.application.name=eventConsumer
server.port=8082

app.kafka.topic.orders=orders
app.processing.rate-per-second=2.0

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=orders-processor-v1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.max.poll.records=1
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.listener.concurrency=1
